### ISSUE TITLE
Field labels enkel leesbaar in dark mode

### ISSUE THREAD

**Issue by IljaCooreman** [koen-ongena-imec/handtekeningkwakker-3000#1]
![image](https://user-images.githubusercontent.com/25901830/221887219-9aba168d-e0a7-48d5-ac52-113ef4c4866b.png)
zo ziet het er uit overdag met een witte achtergrond.

**Comment by koen-ongena-imec** [comment]
Ik heb 'light' mode uitgezet :)

**Comment by koen-ongena-imec** [comment]
Issue solved en deployed over enkele momenten

**Comment by koen-ongena-imec** [comment]
En merci om dit allereerste issue te loggen :)
