### ISSUE TITLE
Signing results in a 'John Doe'

### ISSUE THREAD

**Issue by alherregodts** [koen-ongena-imec/handtekeningkwakker-3000#2]
![image](https://user-images.githubusercontent.com/31988429/221987822-2c39af72-2fae-4e85-b2f8-74cdf6f608d6.png)

I completed all info necessary, including my name, but the stamping results in a John Doe. No idea what I did wrong
![image](https://user-images.githubusercontent.com/31988429/221987940-09941d22-370e-40ea-8e3f-6c8cbf66ebf9.png)

**Comment by koen-ongena-imec** [comment]
Woops, stupid mistake. Fixed in a couple of minutes. As a side effect, the signing date is now identical to the one you specify in the text inputfield, eg 2/28/2023 in the screenshot. I hope that is OK?
