### ISSUE TITLE
Nice to have : would be very nice to have output file when downloaded in a structed format

### ISSUE THREAD

**Issue by alherregodts** [koen-ongena-imec/handtekeningkwakker-3000#3]
I save all my files in a structured format, it would be great to have the output downloaded file as a structured format

e.g. 2023-02 Timesheet Flexforce Jonas de Vrient (Tobania) - signed

![image](https://user-images.githubusercontent.com/31988429/221988471-8203314e-ebe0-4d2c-b40e-687224cae2e6.png)

**Comment by koen-ongena-imec** [comment]
No problem. So the format should be _yyyy-MM - Timesheet flexforce - name (companyName) - signed_, I assume?

**Comment by koen-ongena-imec** [comment]
Done
